project_name: validate-csv

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd
    binary: validate-csv
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE*
      - README*
      - run.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
    - tap:
        owner: 'robinlieb'
        name: 'homebrew-brew'
        token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      folder: 'Formula'
      homepage: 'https://github.com/robinlieb/validate-csv'
      description: 'CLI tool to validate CSV by duplicates and sums of rows.'
      license: 'Apache-2.0'
      commit_author:
        name: robinlieb
        email: robin.j.lieb@gmail.com
      install: bin.install "validate-csv"
dockers:
  - image_templates:
    - robinlieb/validate-csv
    dockerfile: "build.Dockerfile"
    extra_files:
    - run.sh