name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        go version
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Build
      run: make build

    - name: Test
      run: make test
    
    - name: Vet
      run: make vet

    - name: Lint
      run: make lint