name: Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "false"
          fallback-version: "1.0.0"
          skip-version-file: "true"
          skip-commit: "true"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          distribution: goreleaser
          version: latest
          args: |
            release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}